export { default as H1 } from '@typography/H1'
export { default as H2 } from '@typography/H2'
export { default as H3 } from '@typography/H3'
export { default as Lead } from '@typography/Lead'
export { default as H2AndLead } from '@typography/H2AndLead'
