export const textColorVariants = {
  transparent: 'text-transparent',
  white: 'text-white',
  egg: 'text-egg',
  cream: 'text-cream',
  'blue-darker': 'text-blue-darker',
  blue: 'text-blue',
  'blue-light': 'text-blue-light',
  'blue-dark': 'text-blue-dark',
  peach: 'text-peach',
  'peach-light': 'text-peach-light',
  error: 'text-error',
  yellow: 'text-yellow',
  pink: ' text-pink ',
  'pink-light': ' text-pink-light ',
  'pink-lighter': ' text-pink-lighter ',
  pinkLighter: ' text-pinkLighter ',
  wine: 'text-wine',
  banana: 'text-banana',
  'banana-light': 'text-banana-light',
  pinkLight: 'text-pinkLight',
  'wine-100': 'text-wine-100',
  'wine-200': 'text-wine-200',
  'wine-300': 'text-wine-300',
  'wine-400': 'text-wine-400',
  'wine-500': 'text-wine-500',
  current: 'text-current',
  none: '',
}
export type TextColorVariant = keyof typeof textColorVariants

export const backgroundColorVariants = {
  transparent: 'bg-transparent',
  white: 'bg-white',
  egg: 'bg-egg',
  'blue-darker': 'bg-blue-darker',
  blue: 'bg-blue',
  'blue-light': 'bg-blue-light',
  'blue-dark': 'bg-blue-dark',
  peach: 'bg-peach',
  'peach-light': 'bg-peach-light',
  error: 'bg-error',
  yellow: 'bg-yellow',
  pink: 'bg-pink',
  'pink-light': 'bg-pink-light',
  'pink-lighter': 'bg-pink-lighter',
  wine: 'bg-wine',
  'wine-100': 'bg-wine-100',
  'wine-200': 'bg-wine-200',
  'wine-300': 'bg-wine-300',
  'wine-400': 'bg-wine-400',
  'wine-500': 'bg-wine-500',
  current: 'bg-current',
  none: '',
}
export type backgroundColorVariant = keyof typeof backgroundColorVariants
