import Main from '@parts/Main'
import { PropsWithChildren } from 'react'
// case study components
import CaseStudies_Header from '@caseStudies/CaseStudies_Header'
import CaseStudies_Tags from '@caseStudies/CaseStudies_Tags'
import CaseStudies_Credits from '@caseStudies/CaseStudies_Credits'

import CaseStudies_OtherProjects from '@caseStudies/CaseStudies_OtherProjects'
import CaseStudies_BecomeAClient from '@caseStudies/CaseStudies_BecomeAClient'
import CaseStudies_PrevNext from '@caseStudies/CaseStudies_PrevNext'
import CaseStudies_Description from '@caseStudies/CaseStudies_Description'

import Image from 'next/image'
// project info
const title = 'Social Promos'
const tags = [
  { enabled: true, name: 'Creative Concepting', url: '/' },
  { enabled: true, name: 'Motion Design', url: '/' },
  { enabled: true, name: 'Film Production', url: '/' },
]

//client info
const client = 'PupBox'
const clientLogo = '/img/clients/1x/pixelbakery_client_SOLA.png'
const clientURL = 'https://pupbox.com'

// Project Header

const heroVideo = '388595960'
// Sub Head goes right under the title
const projectSubhead = "i'm a big old subheader"
// A quick blurb that goes below the video but above the introduction
const projectExcerpt = 'copy copy copy'
// Long form
const projectIntroduction =
  'PupBox, a subscription box service catering to new puppy owners, already had great content on their social media. The only catch was that it was almost solely generated by their following — subscribers sent in their personal puppy pics to be shared on the feed. While the posts got a lot of attention, they weren’t translating to more subscription sales. <br/> <br/>We came in to produce some content for their feed that combined cute pup vids with informational tidbits and a call to action using some motion elements. The videos provide some in-feed entertainment (who doesn’t love puppies?) while giving the PupBox brand a voice.'

const process =
  'We rounded up three puppies to be our stars and created a few loose story boards to showcase each pup alongside stacks of PupBox subscription boxes.<br/><br/>The biggest thing we’ve learned from working with animals is you can’t go in expecting anything to go the way you planned. However, throughout hours of puppy wrangling (and getting more creative than you ever thought possible in order to get a 2-month-old golden retriever to take a toy out of a box), there’s nothing better than when a magical moment happens on camera.<br/><br/>In post production, we brought in some basic motion elements and color to elevate PupBox’s brand, including bouncy kinetic type and subtle movement for their logo.<br/><br/>We packaged three videos for PupBox to use as native advertising in their social feeds that work toward brand awareness and recognition.'
// credits
const credits = [
  { name: 'Jordan Lambrecht', title: 'Director' },
  { name: 'Karley Johnson', title: 'Executive Producer' },
  { name: 'Tyler Loebig', title: 'Art Director' },
  { name: 'Madeline Christensen', title: 'Animation Lead' },
  { name: 'Hannah Klemme', title: 'Animator' },
  { name: 'Natalie Roetman', title: 'Account Manager' },
  { name: 'Kaitlyn Pfannenstiel', title: 'Account Manager' },
]

function caseStudy_Backcountry_GearheadMagic() {
  return (
    <Main>
      <CaseStudies_Header
        client={client}
        clientURL={clientURL}
        clientLogo={clientLogo}
        projectName={title}
        projectExcerpt={projectExcerpt}
        projectIntroduction={projectIntroduction}
        heroVideo={heroVideo}
        projectSubhead={projectSubhead}
      />
      <CaseStudies_Tags tags={tags} />
      <CaseStudies_Description
        headerColor={'dark-blue'}
        textColor={'cream'}
        bgColor={'blue'}
        header={'Process'}
      >
         <p>
         We rounded up three puppies to be our stars and created a few loose story boards to showcase each pup alongside stacks of PupBox subscription boxes.
        </p>
        <p>
        The biggest thing we’ve learned from working with animals is you can’t go in expecting anything to go the way you planned. However, throughout hours of puppy wrangling (and getting more creative than you ever thought possible in order to get a 2-month-old golden retriever to take a toy out of a box), there’s nothing better than when a magical moment happens on camera.
        </p>
        <p>
        In post production, we brought in some basic motion elements and color to elevate PupBox’s brand, including bouncy kinetic type and subtle movement for their logo. We packaged three videos for PupBox to use as native advertising in their social feeds that work toward brand awareness and recognition.
        </p>
  
      </CaseStudies_Description>

     <CaseStudies_Description header={''} bgColor={'cream'}>
        <div className='grid grid-cols-1 lg:grid-cols-2'>
          <div className='col-span-1 relative h-full w-full'>
            <Image
              src={'/img/work/KN_ECommPromo_SnackPack.gif'}
              layout={'fill'}
              alt={'DESCRIPTION GOES HERE'}
              objectFit={'contain'}
            />
          </div>
        </div>
      </CaseStudies_Description>
      <CaseStudies_Credits credits={credits} />
      <CaseStudies_PrevNext title={title} />

      <CaseStudies_OtherProjects client={client} title={title} />
      <CaseStudies_BecomeAClient />
    </Main>
  )
}

export default caseStudy_Backcountry_GearheadMagic
